# Generated by Django 3.2.6 on 2021-10-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=255)),
                ('commune', models.CharField(max_length=255)),
                ('libelle', models.CharField(max_length=255)),
                ('type_equipement', models.CharField(max_length=255)),
                ('profondeur_cable', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('latitude', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=12, null=True)),
                ('concessionnaire', models.CharField(max_length=255)),
                ('dtce_chambre_proche', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chbre_proche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locale_proches', to='chambres.locale')),
            ],
        ),
    ]
